version: "3.8"
services:
  frontend:
    container_name: frontend
    image: frontend:latest
    build: ./frontend
    ports:
    - target: 5000
      published: 5000
      protocol: tcp

  db: 
    container_name: mysql
    build: ./db
    environment:
      MYSQL_DATABASE: flask-db
      MYSQL_ROOT_PASSWORD: password
    ports:
    - target: 3306
      published: 3306
      protocol: tcp

  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf