version: "3.8"
services:
  service_2:
    container_name: service_2
    image: service_2:latest
    build: ./service_2
    ports:
    - target: 5000
      published: 5000
      protocol: tcp

  backend: 
    container_name: backend
    image: backend:latest
    build: ./backend
    environment:
      MYSQL_DATABASE: flask-db
      MYSQL_ROOT_PASSWORD: password
    ports:
    - target: 3306
      published: 3306
      protocol: tcp

  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf